---
label: Project
hide_body: false
fields:
- type: file
  name: image
  label: Image
  description: Project image
  config:
    maxSize: 64
- type: text
  name: title
  label: Title
  description: Project title
  config:
    required: true
- type: textarea
  name: desc
  label: Description
  description: Project description
  config:
    required: true
- type: text
  name: url
  label: Project url
  config:
    required: true
- type: text
  name: button
  label: Button text
  description: Project button text
  config:
    required: true
pages:
- projects/emmanate-summit.md
- projects/just-get-wet-shopify-site.md
- projects/miserable-media.md
- projects/vanilla-js-match-game.md
- projects/vanilla-js-weather-app.md
- projects/vue-js-flash-card-app.md
- projects/vue-js-movie-watch-list-spa-copy.md
- projects/vue-js-movie-watch-list-spa.md
- projects/vue.js-drum-pad.md
